GET http://localhost:8080/api/todos

###

POST http://localhost:8080/api/todos
Content-Type: application/json

{
    "todo": "Ger 15 armboyggingar uttan pausu."
}

POST http://localhost:8080/api/todos
Content-Type: application/json

{
    "todo": "Dansa í Luux"
}

###

DELETE http://localhost:8080/api/todos
Content-Type: application/json

{
    "todo_id": 825
}